export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

export const GET_USER_ORDER_LIST_REQUEST = 'GET_USER_ORDER_LIST_REQUEST';
export const GET_USER_ORDER_LIST_SUCCESS = 'GET_USER_ORDER_LIST_SUCCESS';
export const GET_USER_ORDER_LIST_FAIL = 'GET_USER_ORDER_LIST_FAIL';

export const GET_USER_ORDERS_REQUEST = 'GET_USER_ORDERS_REQUEST';
export const GET_USER_ORDERS_SUCCESS = 'GET_USER_ORDERS_SUCCESS';
export const GET_USER_ORDERS_FAIL = 'GET_USER_ORDERS_FAIL';
