export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const GET_PRODUCTS_DETAILS_REQUEST = 'GET_PRODUCTS_DETAILS_REQUEST';
export const GET_PRODUCTS_DETAILS_SUCCESS = 'GET_PRODUCTS_DETAILS_SUCCESS';
export const GET_PRODUCTS_DETAILS_FAIL = 'GET_PRODUCTS_DETAILS_FAIL';
export const GET_PRODUCTS_DETAILS_RESET = 'GET_PRODUCTS_DETAILS_RESET';

export const GET_FEATURED_PRODUCTS_REQUEST = 'GET_FEATURED_PRODUCTS_REQUEST';
export const GET_FEATURED_PRODUCTS_SUCCESS = 'GET_FEATURED_PRODUCTS_SUCCESS';
export const GET_FEATURED_PRODUCTS_FAIL = 'GET_FEATURED_PRODUCTS_FAIL';

export const GET_SEARCHED_PRODUCTS_REQUEST = 'GET_SEARCHED_PRODUCTS_REQUEST';
export const GET_SEARCHED_PRODUCTS_SUCCESS = 'GET_SEARCHED_PRODUCTS_SUCCESS';
export const GET_SEARCHED_PRODUCTS_FAIL = 'GET_SEARCHED_PRODUCTS_FAIL';
export const GET_SEARCHED_PRODUCTS_RESET = 'GET_SEARCHED_PRODUCTS_RESET';
